import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Navigation from "@/app/UI/Navigation";

const inter = Inter({subsets: ["latin"]});
const poppins = Poppins({subsets: ["latin"], weight: '500'});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children}) {

    return (
        <html lang="en">

        <body className={poppins.className}>

        <Navigation/>

        <div>{children}</div>
        </body>
        </html>
    );
}
